# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class BaffleSpec(BaseModel):
    mass_kg: float
    instrument: str

class BaffleDesign(BaseModel):
    quantity: int
    placement: Placement | None

class BaffleEntry(BaseModel):
    spec: BaffleSpec
    design: BaffleDesign
    meta: dict[str, object] | None

class BracketSpec(BaseModel):
    mass_kg: float
    material: str

class BracketDesign(BaseModel):
    quantity: int
    placement: Placement | None

class BracketEntry(BaseModel):
    spec: BracketSpec
    design: BracketDesign
    meta: dict[str, object] | None

class CounterMassSpec(BaseModel):
    mass_kg: float

class CounterMassDesign(BaseModel):
    quantity: int
    placement: Placement | None

class CounterMassEntry(BaseModel):
    spec: CounterMassSpec
    design: CounterMassDesign
    meta: dict[str, object] | None

class FastenerSpec(BaseModel):
    mass_kg: float
    material: str

class FastenerDesign(BaseModel):
    quantity: int

class FastenerEntry(BaseModel):
    spec: FastenerSpec
    design: FastenerDesign
    meta: dict[str, object] | None

class FrameSpec(BaseModel):
    mass_kg: float
    material: str
    yield_strength_mpa: float

class FrameDesign(BaseModel):
    quantity: int
    placement: Placement | None

class FrameEntry(BaseModel):
    spec: FrameSpec
    design: FrameDesign
    meta: dict[str, object] | None

class HarnessSpec(BaseModel):
    mass_kg: float

class HarnessDesign(BaseModel):
    quantity: int

class HarnessEntry(BaseModel):
    spec: HarnessSpec
    design: HarnessDesign
    meta: dict[str, object] | None

class HingeSpec(BaseModel):
    mass_kg: float
    deploy_angle_deg: float

class HingeDesign(BaseModel):
    quantity: int
    placement: Placement | None

class HingeEntry(BaseModel):
    spec: HingeSpec
    design: HingeDesign
    meta: dict[str, object] | None

class HoldReleaseMechanismSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    release_mechanism: str

class HoldReleaseMechanismDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class HoldReleaseMechanismEntry(BaseModel):
    spec: HoldReleaseMechanismSpec
    design: HoldReleaseMechanismDesign
    meta: dict[str, object] | None

class SeparationBracketSpec(BaseModel):
    mass_kg: float
    side: str

class SeparationBracketDesign(BaseModel):
    quantity: int
    placement: Placement | None

class SeparationBracketEntry(BaseModel):
    spec: SeparationBracketSpec
    design: SeparationBracketDesign
    meta: dict[str, object] | None

class SeparationConnectorSpec(BaseModel):
    mass_kg: float
    connector_type: str
    contact_count: int

class SeparationConnectorDesign(BaseModel):
    quantity: int
    placement: Placement | None

class SeparationConnectorEntry(BaseModel):
    spec: SeparationConnectorSpec
    design: SeparationConnectorDesign
    meta: dict[str, object] | None

class StructuralPanelSpec(BaseModel):
    mass_kg: float
    material: str
    thickness_mm: float

class StructuralPanelDesign(BaseModel):
    quantity: int
    placement: Placement | None

class StructuralPanelEntry(BaseModel):
    spec: StructuralPanelSpec
    design: StructuralPanelDesign
    meta: dict[str, object] | None
