# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class FrameSpec(BaseModel):
    mass_kg: float
    material: str
    yield_strength_mpa: float

class FrameDesign(BaseModel):
    quantity: int
    placement: Placement | None

class FrameEntry(BaseModel):
    spec: FrameSpec
    design: FrameDesign
    meta: dict[str, object] | None

class StructuralPanelSpec(BaseModel):
    mass_kg: float
    material: str
    thickness_mm: float

class StructuralPanelDesign(BaseModel):
    quantity: int
    placement: Placement | None

class StructuralPanelEntry(BaseModel):
    spec: StructuralPanelSpec
    design: StructuralPanelDesign
    meta: dict[str, object] | None
