"""`schema.stubgen` の単体テストと CLI スモークテスト。"""

import pytest
from typer.testing import CliRunner

from cli.main import app
from core.discovery import discover_systems
from core.stubgen import check_stubs, generate_stubs
from schema import default_registry
from schema.stubgen import STUB_FILENAME, render_subsystem_stub


@pytest.fixture(autouse=True)
def _bootstrap_registry() -> None:
    """system discovery を発火して registry を埋める。"""
    discover_systems()


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


def test_render_subsystem_stub_power() -> None:
    """power の stub に Battery 系 model と field が含まれる。"""
    out = render_subsystem_stub("power")
    assert "# Auto-generated by `craft gen-stubs`" in out
    assert "from pydantic import BaseModel" in out
    assert "class BatterySpec(BaseModel):" in out
    assert "capacity_wh: float" in out
    assert "class BatteryDesign(BaseModel):" in out
    assert "class BatteryEntry(BaseModel):" in out
    # Entry の参照型が短い名前で書かれている
    assert "spec: BatterySpec" in out


def test_render_subsystem_stub_mission_config() -> None:
    """Config は <Name>Model class として書かれる。"""
    out = render_subsystem_stub("mission")
    assert "class MissionProfileModel(BaseModel):" in out
    assert "duration_years: float" in out


def test_generate_stubs_writes_files(tmp_path) -> None:
    """全 system 分のファイルが書き出される。"""
    written = generate_stubs(output_root=tmp_path)
    assert written, "expected at least one stub to be written"
    subs = default_registry.systems()
    for sub in subs:
        expected = tmp_path / sub / STUB_FILENAME
        assert expected in written
        assert expected.exists()
        text = expected.read_text(encoding="utf-8")
        assert text.startswith("# Auto-generated by `craft gen-stubs`")


def test_check_stubs_passes_after_generate(tmp_path) -> None:
    """generate 直後の check は diff 0。"""
    generate_stubs(output_root=tmp_path)
    mismatches = check_stubs(output_root=tmp_path)
    assert mismatches == []


def test_check_stubs_detects_missing(tmp_path) -> None:
    """ファイル未生成なら check は mismatch を返す。"""
    mismatches = check_stubs(output_root=tmp_path)
    assert mismatches, "expected mismatches when no stubs exist"


def test_cli_gen_stubs_check_exit_0_when_synced(runner, tmp_path, monkeypatch) -> None:
    """CLI: generate 直後の --check は exit 0。"""
    import core.stubgen as stubgen

    monkeypatch.setattr(stubgen, "subsystem_dir", lambda name: tmp_path / name)

    write_result = runner.invoke(app, ["gen-stubs"])
    assert write_result.exit_code == 0, write_result.stdout

    check_result = runner.invoke(app, ["gen-stubs", "--check"])
    assert check_result.exit_code == 0, check_result.stdout
    assert "OK" in check_result.stdout


def test_cli_gen_stubs_check_exit_1_when_outdated(runner, tmp_path, monkeypatch) -> None:
    """CLI: stub が無い状態で --check は exit 1。"""
    import core.stubgen as stubgen

    monkeypatch.setattr(stubgen, "subsystem_dir", lambda name: tmp_path / name)

    # tmp_path には何も書かれていない → --check は exit 1
    result = runner.invoke(app, ["gen-stubs", "--check"])
    assert result.exit_code == 1
