# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

class OrbitalParamsModel(BaseModel):
    altitude_km: float
    period_min: float
    eclipse_duration_s: float
