# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class BatterySpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    capacity_wh: float
    capacity_ah: float
    nominal_voltage_v: float
    series_count: int
    parallel_count: int
    max_charge_voltage_v: float
    charge_current_rate_c: float
    internal_resistance_ohm: float
    manufacturer: str

class BatteryDesign(BaseModel):
    quantity: int
    placement: Placement | None
    depth_of_discharge: float

class BatteryRequirements(BaseModel):
    depth_of_discharge_max: float

class BatteryEntry(BaseModel):
    spec: BatterySpec
    design: BatteryDesign
    requirements: BatteryRequirements
    meta: dict[str, object] | None

class PDMSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    rated_current_a: float
    bus_voltage_v: float
    channel_count: int

class PDMDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]
    efficiency: float

class PDMEntry(BaseModel):
    spec: PDMSpec
    design: PDMDesign
    meta: dict[str, object] | None

class SolarPanelSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    area_m2: float
    default_power_generation_per_unit_w: float
    bol_power_w: float
    eol_power_w: float
    efficiency: float
    cell_type: str

class SolarPanelDesign(BaseModel):
    quantity: int
    placement: Placement | None
    cell_count: int
    string_count: int

class SolarPanelEntry(BaseModel):
    spec: SolarPanelSpec
    design: SolarPanelDesign
    meta: dict[str, object] | None
