# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from schema.common import OperationMode

class BatterySpec(BaseModel):
    temp_min_c: float
    temp_max_c: float
    capacity_wh: float
    nominal_voltage_v: float
    manufacturer: str

class BatteryDesign(BaseModel):
    depth_of_discharge: float

class BatteryRequirements(BaseModel):
    depth_of_discharge_max: float

class BatteryEntry(BaseModel):
    spec: BatterySpec
    design: BatteryDesign
    requirements: BatteryRequirements
    meta: dict[str, object] | None

class PDMSpec(BaseModel):
    power_per_unit_w: float
    rated_current_a: float

class PDMDesign(BaseModel):
    power_modes: dict[OperationMode, bool]
    efficiency: float

class PDMEntry(BaseModel):
    spec: PDMSpec
    design: PDMDesign
    meta: dict[str, object] | None

class SolarPanelSpec(BaseModel):
    temp_min_c: float
    temp_max_c: float
    area_m2: float
    default_power_generation_per_unit_w: float
    efficiency: float

class SolarPanelDesign(BaseModel):
    cell_count: int
    string_count: int

class SolarPanelEntry(BaseModel):
    spec: SolarPanelSpec
    design: SolarPanelDesign
    meta: dict[str, object] | None
