# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class PropellantSpec(BaseModel):
    mass_kg: float
    propellant_type: str
    density_kg_per_l: float

class PropellantDesign(BaseModel):
    quantity: int

class PropellantEntry(BaseModel):
    spec: PropellantSpec
    design: PropellantDesign
    meta: dict[str, object] | None

class PropellantTankSpec(BaseModel):
    mass_kg: float
    propellant_type: str
    volume_l: float
    max_pressure_bar: float

class PropellantTankDesign(BaseModel):
    quantity: int
    placement: Placement | None

class PropellantTankEntry(BaseModel):
    spec: PropellantTankSpec
    design: PropellantTankDesign
    meta: dict[str, object] | None

class ThrusterSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    propellant_type: str
    thrust_mn: float
    specific_impulse_s: float
    min_impulse_bit_ns: float

class ThrusterDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class ThrusterEntry(BaseModel):
    spec: ThrusterSpec
    design: ThrusterDesign
    meta: dict[str, object] | None
