# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

class MissionProfileModel(BaseModel):
    duration_years: float
    target_altitude_km: float
    primary_payload: str
    contact_frequency_per_day: int
    launch_window_start: str

class OrbitalParametersModel(BaseModel):
    semi_major_axis_km: float
    eccentricity: float
    inclination_deg: float
    raan_deg: float
    arg_periapsis_deg: float
    mean_anomaly_deg: float
    epoch_utc: str
