# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class ImageProcessorSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    compression_algorithm: str
    frames_per_mission: int
    processing_host: str

class ImageProcessorDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]
    compression_ratio: float

class ImageProcessorEntry(BaseModel):
    spec: ImageProcessorSpec
    design: ImageProcessorDesign
    meta: dict[str, object] | None

class ImageSensorSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    tdi_direction_pixels: int
    cross_track_pixels: int
    pixel_size_m: float
    tdi_stages: int
    tdi_max_stages: int
    line_rate_s: float
    lines_per_frame: int
    frames_per_mission: int
    sensor_type: str
    manufacturer: str

class ImageSensorDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]
    bits_per_pixel: int

class ImageSensorEntry(BaseModel):
    spec: ImageSensorSpec
    design: ImageSensorDesign
    meta: dict[str, object] | None

class MissionInterfaceSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    soc: str
    interface_type: str
    ccsds_packet_protocol: str
    manufacturer: str

class MissionInterfaceDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class MissionInterfaceEntry(BaseModel):
    spec: MissionInterfaceSpec
    design: MissionInterfaceDesign
    meta: dict[str, object] | None

class TelescopeSpec(BaseModel):
    mass_kg: float
    focal_length_m: float
    pixel_size_m: float
    aperture_diameter_m: float
    f_number: float
    ifov_rad: float
    sun_exclusion_angle_deg: float
    earth_exclusion_angle_deg: float
    moon_exclusion_angle_deg: float
    telescope_type: str
    manufacturer: str

class TelescopeDesign(BaseModel):
    quantity: int
    placement: Placement | None

class TelescopeEntry(BaseModel):
    spec: TelescopeSpec
    design: TelescopeDesign
    meta: dict[str, object] | None

class MassPropertiesModel(BaseModel):
    ixx_kg_m2: float
    iyy_kg_m2: float
    izz_kg_m2: float

class MissionProfileModel(BaseModel):
    duration_years: float
    target_altitude_km: float
    primary_payload: str
    contact_frequency_per_day: int
    launch_window_start: str
    flight_mass_kg: float

class OperationModeConfigModel(BaseModel):
    description: str
    max_duration_s: float
    is_initial_mode: bool
    allowed_transitions: list[str]

class OrbitalParametersModel(BaseModel):
    semi_major_axis_km: float
    eccentricity: float
    inclination_deg: float
    raan_deg: float
    arg_periapsis_deg: float
    mean_anomaly_deg: float
    epoch_utc: str
