# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from systems.cdh.components import BusInterface

class OBCSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    clock_mhz: int
    ram_mb: int
    storage_gb: float
    architecture: str
    bus_interface: BusInterface

class OBCDesign(BaseModel):
    quantity: int
    power_modes: dict[str, bool]
    firmware_version: str
    boot_partition_count: int

class OBCRequirements(BaseModel):
    mtbf_hours: float
    radiation_tolerance_krad: float

class OBCEntry(BaseModel):
    spec: OBCSpec
    design: OBCDesign
    requirements: OBCRequirements
    meta: dict[str, object] | None
