# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from schema.common import OperationMode
from subsystems.cdh.components import BusInterface

class OBCSpec(BaseModel):
    operating_temperature_min_c: float
    operating_temperature_max_c: float
    default_power_consumption_per_unit_w: float
    clock_mhz: int
    ram_mb: int
    storage_gb: float
    architecture: str
    bus_interface: BusInterface

class OBCDesign(BaseModel):
    power_modes: dict[OperationMode, bool]
    firmware_version: str
    boot_partition_count: int

class OBCRequirements(BaseModel):
    mtbf_hours: float
    radiation_tolerance_krad: float

class OBCEntry(BaseModel):
    spec: OBCSpec
    design: OBCDesign
    requirements: OBCRequirements
    meta: dict[str, object] | None
