# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class GNSSAntennaSpec(BaseModel):
    mass_kg: float
    band: str
    gain_dbi: float
    half_angle_deg: float

class GNSSAntennaDesign(BaseModel):
    quantity: int
    placement: Placement | None

class GNSSAntennaEntry(BaseModel):
    spec: GNSSAntennaSpec
    design: GNSSAntennaDesign
    meta: dict[str, object] | None

class GNSSReceiverSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    constellation: str
    channel_count: int
    update_rate_hz: float
    position_noise_m: float

class GNSSReceiverDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class GNSSReceiverEntry(BaseModel):
    spec: GNSSReceiverSpec
    design: GNSSReceiverDesign
    meta: dict[str, object] | None

class GyroscopeSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    bias_stability_deg_per_h: float
    grade: str

class GyroscopeDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class GyroscopeEntry(BaseModel):
    spec: GyroscopeSpec
    design: GyroscopeDesign
    meta: dict[str, object] | None

class MagneticTorquerSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    max_dipole_moment_am2: float

class MagneticTorquerDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class MagneticTorquerEntry(BaseModel):
    spec: MagneticTorquerSpec
    design: MagneticTorquerDesign
    meta: dict[str, object] | None

class MagnetometerSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    range_ut: float
    noise_nt: float

class MagnetometerDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class MagnetometerEntry(BaseModel):
    spec: MagnetometerSpec
    design: MagnetometerDesign
    meta: dict[str, object] | None

class ReactionWheelSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    max_torque_nms: float
    max_momentum_nms: float
    rotor_inertia_kg_m2: float
    max_speed_rpm: float

class ReactionWheelDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class ReactionWheelEntry(BaseModel):
    spec: ReactionWheelSpec
    design: ReactionWheelDesign
    meta: dict[str, object] | None

class StarTrackerSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    accuracy_arcsec: float
    fov_deg: float
    update_rate_hz: float
    sun_exclusion_deg: float
    earth_exclusion_deg: float

class StarTrackerDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class StarTrackerEntry(BaseModel):
    spec: StarTrackerSpec
    design: StarTrackerDesign
    meta: dict[str, object] | None

class SunSenserSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    fov_deg: float

class SunSenserDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class SunSenserEntry(BaseModel):
    spec: SunSenserSpec
    design: SunSenserDesign
    meta: dict[str, object] | None

class DisturbanceModelModel(BaseModel):
    reference_area_m2: float
    drag_coefficient: float
    cp_cg_offset_m: float
    atmospheric_density_kg_m3: float
    pointing_error_deg: float
    momentum_margin: float
