# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class GyroscopeSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    bias_stability_deg_per_h: float
    grade: str

class GyroscopeDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class GyroscopeEntry(BaseModel):
    spec: GyroscopeSpec
    design: GyroscopeDesign
    meta: dict[str, object] | None

class MagneticTorquerSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    max_dipole_moment_am2: float

class MagneticTorquerDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class MagneticTorquerEntry(BaseModel):
    spec: MagneticTorquerSpec
    design: MagneticTorquerDesign
    meta: dict[str, object] | None

class MagnetometerSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    range_ut: float
    noise_nt: float

class MagnetometerDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class MagnetometerEntry(BaseModel):
    spec: MagnetometerSpec
    design: MagnetometerDesign
    meta: dict[str, object] | None

class ReactionWheelSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    max_torque_nms: float
    max_momentum_nms: float

class ReactionWheelDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class ReactionWheelEntry(BaseModel):
    spec: ReactionWheelSpec
    design: ReactionWheelDesign
    meta: dict[str, object] | None

class StarTrackerSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    accuracy_arcsec: float
    fov_deg: float
    update_rate_hz: float

class StarTrackerDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class StarTrackerEntry(BaseModel):
    spec: StarTrackerSpec
    design: StarTrackerDesign
    meta: dict[str, object] | None

class SunSenserSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    fov_deg: float

class SunSenserDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class SunSenserEntry(BaseModel):
    spec: SunSenserSpec
    design: SunSenserDesign
    meta: dict[str, object] | None
