# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

class SunSenserSpec(BaseModel):
    mass_kg: float
    fov_deg: float


class SunSenserDesign(BaseModel):
    quantity: int


class SunSenserEntry(BaseModel):
    spec: SunSenserSpec
    design: SunSenserDesign
    meta: dict[str, object] | None
