"""Component / Config の `.pyi` stub 生成。

`UnifiedRegistry` に登録済みの Pydantic モデル (Spec / Design / Requirements / Entry,
および Config の Model) を、system ごとに 1 ファイルの `.pyi` 形式で書き出す。

Output:
    `systems/<sub>/_stubs.pyi` （`_stubs` 接頭辞で通常 import 経路と衝突しない）

主な API:
    `render_subsystem_stub(system) -> str` — 1 system 分の文字列を生成
    `generate_stubs(output_root=None) -> list[Path]` — 全 system を書き出す
    `check_stubs() -> list[tuple[Path, str]]` — 既存ファイルとの diff を返す
"""

import difflib
import subprocess
import sys
import types
import typing
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from core.discovery import discover_systems
from core.paths import subsystem_dir
from schema.registry import (
    ComponentDefinition,
    ConfigDefinition,
    UnifiedRegistry,
    default_registry,
)

STUB_FILENAME = "_stubs.pyi"
_HEADER = "# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY\n"
_BASE_IMPORT = "from pydantic import BaseModel\n"


def _apply_ruff_format(content: str) -> str:
    """ruff format を content 文字列に適用して返す。ruff がなければそのまま返す。"""
    ruff = Path(sys.executable).parent / "ruff"
    try:
        result = subprocess.run(
            [str(ruff), "format", "--stdin-filename", STUB_FILENAME, "-"],
            input=content,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout
    except FileNotFoundError:
        pass
    return content


def _format_annotation(
    annotation: Any,
    imports: dict[str, set[str]],
    local_models: set[str],
) -> str:
    """Pydantic field の annotation 型を `.pyi` 用文字列に整形する。

    `imports` には外部参照を `{module: {name, ...}}` として追記する。
    `local_models` はこのファイル内で定義する BaseModel 派生の名前集合。
    そこに含まれない BaseModel 派生は外部 import として登録される。

    - 同一ファイル内 BaseModel 派生は short name のみ
    - 外部 BaseModel 派生（例: ユーザ定義のネスト model）は import を追加
    - `X | Y` / `Optional[X]` などの Union は `X | Y` 形式
    - `dict[K, V]`, `list[T]`, `tuple[...]` などのジェネリックは再帰整形
    - `typing.Any` は `object` として出力（stub 用に簡潔に）
    """
    # typing.Any は Python 3.14 で `isinstance(Any, type)` が True を返すため先に判定
    if annotation is Any:
        return "object"

    # Plain class
    if isinstance(annotation, type):
        if annotation is type(None):
            return "None"
        if issubclass(annotation, BaseModel):
            if annotation.__name__ not in local_models:
                imports.setdefault(annotation.__module__, set()).add(annotation.__name__)
            return annotation.__name__
        if annotation.__module__ != "builtins":
            imports.setdefault(annotation.__module__, set()).add(annotation.__name__)
        return annotation.__name__

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    # Union / Optional
    if origin is typing.Union or origin is types.UnionType:
        return " | ".join(_format_annotation(a, imports, local_models) for a in args)

    if origin is not None:
        origin_name = _format_origin(origin)
        if args:
            inner = ", ".join(_format_annotation(a, imports, local_models) for a in args)
            return f"{origin_name}[{inner}]"
        return origin_name

    # フォールバック（Literal などの非 type）
    return repr(annotation)


def _format_origin(origin: Any) -> str:
    """`typing.get_origin` の戻り値を文字列化。"""
    if isinstance(origin, type):
        return origin.__name__
    # typing.Literal, typing.ClassVar など
    return str(origin).replace("typing.", "")


def _render_model_class(
    model: type[BaseModel],
    imports: dict[str, set[str]],
    local_models: set[str],
) -> str:
    """1 つの Pydantic model を `class Name(BaseModel): ...` 形式に整形。"""
    lines = [f"class {model.__name__}(BaseModel):"]
    fields = model.model_fields
    if not fields:
        lines.append("    pass")
        return "\n".join(lines) + "\n"

    for fname, finfo in fields.items():
        type_str = _format_annotation(finfo.annotation, imports, local_models)
        lines.append(f"    {fname}: {type_str}")
    return "\n".join(lines) + "\n"


def _render_imports(imports: dict[str, set[str]]) -> str:
    """外部参照クラスの import 行を生成する（決定論的に並べる）。"""
    if not imports:
        return ""
    lines: list[str] = []
    for module in sorted(imports):
        names = sorted(imports[module])
        lines.append(f"from {module} import {', '.join(names)}\n")
    return "".join(lines)


def _collect_models_for_component(defn: ComponentDefinition) -> list[type[BaseModel]]:
    """Component 1 つに紐づく全 Pydantic model を順に返す。"""
    out: list[type[BaseModel]] = [defn.spec]
    if defn.design is not None:
        out.append(defn.design)
    if defn.requirements is not None:
        out.append(defn.requirements)
    out.append(defn.entry)
    return out


def _collect_models_for_config(defn: ConfigDefinition) -> list[type[BaseModel]]:
    return [defn.model]


def render_subsystem_stub(
    system: str,
    *,
    registry: UnifiedRegistry | None = None,
) -> str:
    """1 system 分の `.pyi` 文字列を生成する（書き込みなし）。"""
    reg = registry if registry is not None else default_registry

    components = sorted(reg.components(system=system), key=lambda d: d.name)
    configs = sorted(reg.configs(system=system), key=lambda d: d.name)

    # ファイル内で定義する model 名を先に集める（外部参照と区別するため）
    local_models: set[str] = set()
    for cdef in components:
        for model in _collect_models_for_component(cdef):
            local_models.add(model.__name__)
    for cdef in configs:
        for model in _collect_models_for_config(cdef):
            local_models.add(model.__name__)

    imports: dict[str, set[str]] = {}
    blocks: list[str] = []
    for cdef in components:
        for model in _collect_models_for_component(cdef):
            blocks.append(_render_model_class(model, imports, local_models))
    for cdef in configs:
        for model in _collect_models_for_config(cdef):
            blocks.append(_render_model_class(model, imports, local_models))

    # pydantic は _BASE_IMPORT で既に入っているので除外して重複を防ぐ
    imports.pop("pydantic", None)

    header_parts: list[str] = [_HEADER, _BASE_IMPORT]
    extra_imports = _render_imports(imports)
    if extra_imports:
        # ruff (I001): third-party と first-party の間に空行
        header_parts.append("\n")
        header_parts.append(extra_imports)
    header_parts.append("\n")

    if not blocks:
        return "".join(header_parts)

    body = "\n\n".join(blocks)
    if not body.endswith("\n"):
        body += "\n"
    return "".join(header_parts) + body


def _stub_path_for(system: str, *, output_root: Path | None = None) -> Path:
    if output_root is None:
        return subsystem_dir(system) / STUB_FILENAME
    return output_root / system / STUB_FILENAME


def _ensure_bootstrap(registry: UnifiedRegistry | None) -> UnifiedRegistry:
    """default_registry を使う場合は system discovery を発火させる。"""
    if registry is not None:
        return registry
    # systems を import して registry を埋める
    discover_systems()
    return default_registry


def generate_stubs(
    *,
    output_root: Path | None = None,
    registry: UnifiedRegistry | None = None,
) -> list[Path]:
    """全 system の stub を生成し、書き込んだファイルパスのリストを返す。

    `output_root` を指定すると `<output_root>/<sub>/_stubs.pyi` に書き出す。
    省略時は `systems/<sub>/_stubs.pyi`。
    """
    reg = _ensure_bootstrap(registry)
    written: list[Path] = []
    for sub in sorted(reg.systems()):
        content = _apply_ruff_format(render_subsystem_stub(sub, registry=reg))
        path = _stub_path_for(sub, output_root=output_root)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def check_stubs(
    *,
    output_root: Path | None = None,
    registry: UnifiedRegistry | None = None,
) -> list[tuple[Path, str]]:
    """既存 stub と生成結果を比較し、ずれているファイル (path, diff) のリストを返す。

    diff は `difflib.unified_diff` 形式。出力が一致すれば空リスト。
    """
    reg = _ensure_bootstrap(registry)
    mismatches: list[tuple[Path, str]] = []
    for sub in sorted(reg.systems()):
        expected = _apply_ruff_format(render_subsystem_stub(sub, registry=reg))
        path = _stub_path_for(sub, output_root=output_root)
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            diff = "".join(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=f"{path} (expected)",
                )
            )
            mismatches.append((path, diff))
    return mismatches
