# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class AntennaSpec(BaseModel):
    mass_kg: float
    band: str
    gain_dbi: float
    polarization: str
    direction: str

class AntennaDesign(BaseModel):
    quantity: int
    placement: Placement | None

class AntennaEntry(BaseModel):
    spec: AntennaSpec
    design: AntennaDesign
    meta: dict[str, object] | None

class TransceiverSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    band: str
    direction: str
    frequency_mhz: float
    tx_power_w: float
    data_rate_kbps: float
    modulation: str

class TransceiverDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class TransceiverEntry(BaseModel):
    spec: TransceiverSpec
    design: TransceiverDesign
    meta: dict[str, object] | None
