# Auto-generated by `craft gen-stubs` — DO NOT EDIT MANUALLY
from pydantic import BaseModel

from craft.schema.dsl.placement import Placement

class FFControllerSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    clock_mhz: int
    ram_mb: int
    storage_gb: float

class FFControllerDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class FFControllerEntry(BaseModel):
    spec: FFControllerSpec
    design: FFControllerDesign
    meta: dict[str, object] | None

class GNSSAntennaSpec(BaseModel):
    mass_kg: float
    band: str
    gain_dbi: float

class GNSSAntennaDesign(BaseModel):
    quantity: int
    placement: Placement | None

class GNSSAntennaEntry(BaseModel):
    spec: GNSSAntennaSpec
    design: GNSSAntennaDesign
    meta: dict[str, object] | None

class GNSSReceiverSpec(BaseModel):
    mass_kg: float
    temp_min_c: float
    temp_max_c: float
    power_per_unit_w: float
    constellation: str
    channel_count: int
    update_rate_hz: float

class GNSSReceiverDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class GNSSReceiverEntry(BaseModel):
    spec: GNSSReceiverSpec
    design: GNSSReceiverDesign
    meta: dict[str, object] | None

class OpticalLEDSpec(BaseModel):
    mass_kg: float
    power_per_unit_w: float
    wavelength_nm: float
    optical_power_w: float
    beam_angle_deg: float

class OpticalLEDDesign(BaseModel):
    quantity: int
    placement: Placement | None
    power_modes: dict[str, bool]

class OpticalLEDEntry(BaseModel):
    spec: OpticalLEDSpec
    design: OpticalLEDDesign
    meta: dict[str, object] | None

class OpticalMirrorSpec(BaseModel):
    mass_kg: float
    reflectivity: float
    diameter_mm: float
    mirror_type: str

class OpticalMirrorDesign(BaseModel):
    quantity: int
    placement: Placement | None

class OpticalMirrorEntry(BaseModel):
    spec: OpticalMirrorSpec
    design: OpticalMirrorDesign
    meta: dict[str, object] | None
